import {LightAppColors} from '../variables';

export default {
  Colors: {
    primaryDark: LightAppColors.primaryDark,
    primaryLight: LightAppColors.primaryLight,
    primary: LightAppColors.primary,
    secondary: LightAppColors.secondary,
    white: LightAppColors.white,
    black: LightAppColors.black,
    grey0: LightAppColors.grey0,
    grey1: LightAppColors.grey1,
    grey2: LightAppColors.grey2,
    grey3: LightAppColors.grey3,
    grey4: LightAppColors.grey4,
    grey5: LightAppColors.grey5,
    grey6: LightAppColors.grey6,
    greyOutline: LightAppColors.greyOutline,
    greyVeryDark: LightAppColors.greyVeryDark,
    greyVeryLight: LightAppColors.greyVeryLight,
    searchBg: LightAppColors.searchBg,
    success: LightAppColors.success,
    error: LightAppColors.error,
    warning: LightAppColors.warning,
    divider: LightAppColors.divider,
    bagText: LightAppColors.error,
    homeButtonBg: LightAppColors.homeButtonBg,
    homeButtonBg_2: LightAppColors.homeButtonBg_2,
    buttonPrimary: LightAppColors.buttonPrimary,
    buttonSecondary: LightAppColors.buttonSecondary,
    clear: LightAppColors.clear,
    red: LightAppColors.red,
    vividOrange: LightAppColors.vividOrange,
    veryPaleOrange: LightAppColors.veryPaleOrange,
    strongGreen: LightAppColors.strongGreen,
    veryPaleGreen: LightAppColors.veryPaleGreen,
    brightBlue: LightAppColors.brightBlue,
    veryPaleBlue: LightAppColors.veryPaleBlue,
    platform: {
      ios: {
        primary: LightAppColors.primary,
        secondary: LightAppColors.secondary,
        grey: LightAppColors.grey0,
        searchBg: LightAppColors.searchBg,
        success: LightAppColors.success,
        error: LightAppColors.error,
        warning: LightAppColors.warning,
      },
      android: {},
    },
    chart1: LightAppColors.chart1,
    chart2: LightAppColors.chart2,
    chart3: LightAppColors.chart3,
    chart4: LightAppColors.chart4,
    chart5: LightAppColors.chart5,
    chart6: LightAppColors.chart6,
    chart7: LightAppColors.chart7,
    chart8: LightAppColors.chart8,
    order_status_1: LightAppColors.order_status_1,
    order_status_2: LightAppColors.order_status_2,
    order_status_3: LightAppColors.order_status_3,
    order_status_4: LightAppColors.order_status_4,
    order_status_5: LightAppColors.order_status_5,
    order_status_6: LightAppColors.order_status_6,
    order_status_7: LightAppColors.order_status_7,
    order_status_8: LightAppColors.order_status_8,
  },
};
